//! Standalone CLI project generator.
//!
//! `ProjectGenerator` scaffolds a new Cargo binary project whose `main.rs`
//! uses `api2cli` as a library to build and run the dynamic CLI at runtime.
//!
//! The generated project compiles to a self-contained binary that, when
//! executed, loads the spec from the same URL or path that was provided to
//! `api2cli generate`, dynamically assembles the command tree, and dispatches
//! the HTTP request.

use std::path::{Path, PathBuf};

use crate::error::Result;

/// Configuration for the project generator.
#[derive(Debug, Clone)]
pub struct ProjectGenerator {
    /// CLI application name (also the Cargo package and binary name).
    pub app_name: String,
    /// URL or file path to the OpenAPI spec embedded in the generated binary.
    pub spec_source: String,
    /// Directory where the new project folder will be created.
    pub output_dir: PathBuf,
}

impl ProjectGenerator {
    /// Scaffold the project on disk and print next-step instructions.
    ///
    /// Creates:
    /// ```text
    /// <output_dir>/<app_name>/
    ///   Cargo.toml
    ///   src/main.rs
    ///   .gitignore
    /// ```
    pub fn generate(&self) -> Result<()> {
        let project_dir = self.output_dir.join(&self.app_name);
        let src_dir = project_dir.join("src");

        std::fs::create_dir_all(&src_dir)?;

        std::fs::write(project_dir.join("Cargo.toml"), self.cargo_toml())?;
        std::fs::write(src_dir.join("main.rs"), self.main_rs())?;
        std::fs::write(project_dir.join(".gitignore"), GITIGNORE)?;

        self.print_summary(&project_dir);
        Ok(())
    }

    // ── Template renderers ────────────────────────────────────────────────────

    fn cargo_toml(&self) -> String {
        let name = &self.app_name;
        format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
description = "Auto-generated CLI from OpenAPI spec"

[[bin]]
name = "{name}"
path = "src/main.rs"

[dependencies]
api2cli = {{ git = "https://github.com/Binlogo/api2cli" }}
anyhow = "1.0"
"#
        )
    }

    fn main_rs(&self) -> String {
        let app_name = &self.app_name;
        let spec_source = &self.spec_source;
        format!(
            r#"//! {app_name} — auto-generated CLI from <{spec_source}>
//!
//! Generated by api2cli <https://github.com/Binlogo/api2cli>

fn main() -> anyhow::Result<()> {{
    api2cli::DynamicCli::new(api2cli::DynamicCliConfig {{
        spec_source: "{spec_source}".to_string(),
        app_name: "{app_name}".to_string(),
        base_url_override: None,
        auth_token: None,
        output_format: api2cli::OutputFormat::Pretty,
    }})?
    .run()?;
    Ok(())
}}
"#
        )
    }

    fn print_summary(&self, project_dir: &Path) {
        let name = &self.app_name;
        let dir = project_dir.display();
        eprintln!();
        eprintln!(
            "  {} Generated project: {}",
            "✓".green(),
            dir
        );
        eprintln!();
        eprintln!("  Next steps:");
        eprintln!("    cd {name}");
        eprintln!("    cargo build --release");
        eprintln!("    ./target/release/{name} --help");
        eprintln!();
    }
}

// Shared .gitignore content for generated projects.
const GITIGNORE: &str = "/target\n";

// Bring `green()` into scope for the summary printer.
use colored::Colorize as _;

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn generates_project_structure() {
        let tmp = tempfile::tempdir().unwrap();

        let gen = ProjectGenerator {
            app_name: "myapi".to_string(),
            spec_source: "https://api.example.com/openapi.json".to_string(),
            output_dir: tmp.path().to_path_buf(),
        };
        gen.generate().unwrap();

        let project = tmp.path().join("myapi");
        assert!(project.join("Cargo.toml").exists());
        assert!(project.join("src").join("main.rs").exists());
        assert!(project.join(".gitignore").exists());

        let cargo_toml = fs::read_to_string(project.join("Cargo.toml")).unwrap();
        assert!(cargo_toml.contains("name = \"myapi\""));
        assert!(cargo_toml.contains("api2cli"));

        let main_rs = fs::read_to_string(project.join("src/main.rs")).unwrap();
        assert!(main_rs.contains("myapi"));
        assert!(main_rs.contains("api.example.com"));
    }

    #[test]
    fn cargo_toml_contains_correct_name() {
        let gen = ProjectGenerator {
            app_name: "petstore".to_string(),
            spec_source: "https://petstore.swagger.io/v2/swagger.json".to_string(),
            output_dir: PathBuf::from("/tmp"),
        };
        let toml = gen.cargo_toml();
        assert!(toml.contains("name = \"petstore\""));
        assert!(toml.contains("[[bin]]"));
    }
}
